version: '3.3'

services:
   db:
     image: mysql:5.7
     command: mysqld --sql_mode=""
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     ports:
       - 3306:3306

     environment:
       MYSQL_ROOT_PASSWORD: 123456

volumes:
    db_data: {}